Add Tron address functions to Query Engine docs
duneanalytics/dune-api-docs pull request #84
Opened 2024-03-26 17:07 UTC by dsalv

2024-03-26 17:07 UTC, dsalv commented
* **#84** <a href="https://app.graphite.dev/github/pr/duneanalytics/dune-api-docs/84?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dsalv and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-26 19:55 UTC, hawkaa approved these changes
I didn't look up the already existing documentation for the other UDFs. I trust that you've checked and they follow the same format. I had one comment about the title of the page.

2024-03-26 19:55 UTC, hawkaa commented on query-engine/Functions-and-operators/index.mdx
> +- [TronAddress](/query-engine/Functions-and-operators/tronaddress)
Is this the title used in the sidebar? Could "Tron Address Functions" be a better name?

2024-03-27 07:49 UTC, dsalv commented on query-engine/Functions-and-operators/index.mdx
> +- [TronAddress](/query-engine/Functions-and-operators/tronaddress)
That's better, changed

2024-03-27 08:27 UTC, helanto requested changes
I believe there is a typo!

2024-03-27 08:27 UTC, helanto commented on query-engine/Functions-and-operators/tronaddress.mdx
> +Under basic ss58 encoding format an address can be encoded as:
`ss58` ??

2024-03-27 08:51 UTC, dsalv commented on query-engine/Functions-and-operators/tronaddress.mdx
> +Under basic ss58 encoding format an address can be encoded as:
/goodcatch

2024-03-27 09:01 UTC, helanto approved these changes

2024-03-27 09:44 UTC, merged